export const ROUTES = {
  home: "/",
  about: "/about",
  preRegistration: "/pre-registration",
  preRegistrationLegacy: "/oldindan-royxat",
  feedback: "/taklif",
  contact: "/contact",
  contactLegacy: "/aloqa",
  pricing: "/pricing",
  pricingLegacy: "/tariff",
  forSellers: "/for-sellers",
  forShops: "/for-shops",
  forSuppliers: "/for-suppliers",
  forWarehouses: "/for-warehouses",
  forCouriers: "/for-couriers",
  forBuyers: "/for-buyers",
} as const;
