/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TariffRouteImport } from './routes/tariff'
import { Route as TaklifRouteImport } from './routes/taklif'
import { Route as OldindanRoyxatRouteImport } from './routes/oldindan-royxat'
import { Route as AloqaRouteImport } from './routes/aloqa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'

const TariffRoute = TariffRouteImport.update({
  id: '/tariff',
  path: '/tariff',
  getParentRoute: () => rootRouteImport,
} as any)
const TaklifRoute = TaklifRouteImport.update({
  id: '/taklif',
  path: '/taklif',
  getParentRoute: () => rootRouteImport,
} as any)
const OldindanRoyxatRoute = OldindanRoyxatRouteImport.update({
  id: '/oldindan-royxat',
  path: '/oldindan-royxat',
  getParentRoute: () => rootRouteImport,
} as any)
const AloqaRoute = AloqaRouteImport.update({
  id: '/aloqa',
  path: '/aloqa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aloqa': typeof AloqaRoute
  '/oldindan-royxat': typeof OldindanRoyxatRoute
  '/taklif': typeof TaklifRoute
  '/tariff': typeof TariffRoute
  '/admin/feedback': typeof AdminFeedbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aloqa': typeof AloqaRoute
  '/oldindan-royxat': typeof OldindanRoyxatRoute
  '/taklif': typeof TaklifRoute
  '/tariff': typeof TariffRoute
  '/admin/feedback': typeof AdminFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aloqa': typeof AloqaRoute
  '/oldindan-royxat': typeof OldindanRoyxatRoute
  '/taklif': typeof TaklifRoute
  '/tariff': typeof TariffRoute
  '/admin/feedback': typeof AdminFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aloqa'
    | '/oldindan-royxat'
    | '/taklif'
    | '/tariff'
    | '/admin/feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aloqa'
    | '/oldindan-royxat'
    | '/taklif'
    | '/tariff'
    | '/admin/feedback'
  id:
    | '__root__'
    | '/'
    | '/aloqa'
    | '/oldindan-royxat'
    | '/taklif'
    | '/tariff'
    | '/admin/feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AloqaRoute: typeof AloqaRoute
  OldindanRoyxatRoute: typeof OldindanRoyxatRoute
  TaklifRoute: typeof TaklifRoute
  TariffRoute: typeof TariffRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tariff': {
      id: '/tariff'
      path: '/tariff'
      fullPath: '/tariff'
      preLoaderRoute: typeof TariffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taklif': {
      id: '/taklif'
      path: '/taklif'
      fullPath: '/taklif'
      preLoaderRoute: typeof TaklifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oldindan-royxat': {
      id: '/oldindan-royxat'
      path: '/oldindan-royxat'
      fullPath: '/oldindan-royxat'
      preLoaderRoute: typeof OldindanRoyxatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aloqa': {
      id: '/aloqa'
      path: '/aloqa'
      fullPath: '/aloqa'
      preLoaderRoute: typeof AloqaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AloqaRoute: AloqaRoute,
  OldindanRoyxatRoute: OldindanRoyxatRoute,
  TaklifRoute: TaklifRoute,
  TariffRoute: TariffRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
